#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# ASCII Art Banner
echo -e "${RED}"
cat << "EOF"
 ░█████╗░██╗░░░░░░█████╗░██╗░░░██╗██████╗░███████╗███╗░░░███╗░█████╗░██████╗░░██████╗
 ██╔══██╗██║░░░░░██╔══██╗██║░░░██║██╔══██╗██╔════╝████╗░████║██╔══██╗██╔══██╗██╔════╝
 ██║░░╚═╝██║░░░░░███████║██║░░░██║██║░░██║█████╗░░██╔████╔██║██║░░██║██║░░██║╚█████╗░
 ██║░░██╗██║░░░░░██╔══██║██║░░░██║██║░░██║██╔══╝░░██║╚██╔╝██║██║░░██║██║░░██║░╚═══██╗
 ╚█████╔╝███████╗██║░░██║╚██████╔╝██████╔╝███████╗██║░╚═╝░██║╚█████╔╝██████╔╝██████╔╝
 ░╚════╝░╚══════╝╚═╝░░░░░░╚═════╝░╚══════╝░╚══════╝╚═╝░░░░░╚═╝░╚════╝░╚═════╝░╚═════╝░
EOF

echo -e "${CYAN}"
echo "           ClaudeMods Vanilla Arch Kde Systemd-boot to CachyOS Kde Systemd-boot v1.0 24-10-2025"
echo -e "${NC}"
echo "================================================================================"
echo ""

# Function for colored output
print_status() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

print_info() {
    echo -e "${CYAN}[i]${NC} $1"
}

print_section() {
    echo -e "${BLUE}${BOLD}[=== $1 ===]${NC}"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
    print_error "This script should not be run as root. Please run as regular user."
    exit 1
fi

# Warning message
echo -e "${YELLOW}${BOLD}"
echo "WARNING: This script will perform major system modifications including:"
echo "• Adding CachyOS repositories"
echo "• Installing 1000+ packages"
echo "• Modifying bootloader configuration"
echo "• Changing system themes and configurations"
echo -e "${NC}"
echo -e "${RED}${BOLD}Ensure you have backups and understand the risks before proceeding!${NC}"
echo ""

read -p "Do you want to continue? (yes/no): " confirm
if [[ $confirm != "yes" ]]; then
    print_error "Installation cancelled by user."
    exit 0
fi

# Check and remove virt-manager if installed
print_section "Checking for virt-manager"
if pacman -Qi virt-manager &>/dev/null; then
    print_info "virt-manager found, removing it..."
    sudo pacman -Rns --noconfirm virt-manager
    print_status "virt-manager removed successfully"
else
    print_info "virt-manager not installed, proceeding..."
fi

print_section "Starting CachyOS Conversion Process"

# Step 1: Download and setup CachyOS repositories
print_section "Step 1: Setting up CachyOS Repositories"
print_info "Downloading CachyOS repository package..."
curl https://mirror.cachyos.org/cachyos-repo.tar.xz -o cachyos-repo.tar.xz
print_status "Download completed"

print_info "Extracting repository files..."
tar xvf cachyos-repo.tar.xz && cd cachyos-repo
print_status "Extraction completed"

print_info "Running CachyOS repository setup..."
sudo ./cachyos-repo.sh
print_status "Repository setup completed"

# Step 2: Massive package installation
print_section "Step 2: Installing Packages"
print_info "Starting installation (this will take a while)..."
print_info "Please be patient as this process may take 30-60 minutes..."

sudo pacman -S --needed \
a52dec \
aalib \
abseil-cpp \
accounts-qml-module \
accountsservice \
acl \
adobe-source-han-sans-cn-fonts \
adobe-source-han-sans-jp-fonts \
adobe-source-han-sans-kr-fonts \
adwaita-cursors \
adwaita-fonts \
adwaita-icon-theme \
adwaita-icon-theme-legacy \
aha \
alacritty \
alsa-card-profiles \
alsa-firmware \
alsa-lib \
alsa-plugins \
alsa-topology-conf \
alsa-ucm-conf \
alsa-utils \
amd-ucode \
ananicy-cpp \
aom \
appstream \
appstream-qt \
archlinux-keyring \
aribb24 \
aribb25 \
ark \
at-spi2-core \
atkmm \
attica \
attr \
audit \
aurorae \
autoconf \
automake \
avahi \
awesome-terminal-fonts \
baloo \
baloo-widgets \
base \
base-devel \
bash \
bash-completion \
bat \
bind \
binutils \
bison \
blas \
bluedevil \
bluez \
bluez-hid2hci \
bluez-libs \
bluez-qt \
bluez-utils \
bolt \
bpf \
breeze \
breeze-gtk \
breeze-icons \
brotli \
btop \
btrfs-progs \
bubblewrap \
bzip2 \
ca-certificates \
ca-certificates-mozilla \
ca-certificates-utils \
cachyos-alacritty-config \
cachyos-ananicy-rules \
cachyos-emerald-kde-theme-git \
cachyos-fish-config \
cachyos-hello \
cachyos-hooks \
cachyos-iridescent-kde \
cachyos-kde-settings \
cachyos-kernel-manager \
cachyos-keyring \
cachyos-micro-settings \
cachyos-mirrorlist \
cachyos-nord-kde-theme-git \
cachyos-packageinstaller \
cachyos-plymouth-bootanimation \
cachyos-rate-mirrors \
cachyos-settings \
cachyos-themes-sddm \
cachyos-v3-mirrorlist \
cachyos-v4-mirrorlist \
cachyos-wallpapers \
cachyos-zsh-config \
cairo \
cairomm \
cairomm-1.16 \
cantarell-fonts \
capitaine-cursors \
cblas \
cdparanoia \
cfitsio \
char-white \
chromaprint \
chwd \
cifs-utils \
clang \
clinfo \
compiler-rt \
confuse \
convertlit \
coreutils \
cpupower \
cryptsetup \
curl \
dav1d \
db5.3 \
dbus \
dbus-broker \
dbus-broker-units \
dbus-units \
dconf \
ddcutil \
debugedit \
default-cursors \
desktop-file-utils \
device-mapper \
dhclient \
diffutils \
ding-libs \
dmidecode \
dmraid \
dnsmasq \
dnssec-anchors \
dolphin \
dosfstools \
double-conversion \
duf \
duktape \
e2fsprogs \
ebook-tools \
editorconfig-core-c \
efibootmgr \
efitools \
efivar \
egl-wayland \
eglexternalplatform \
ell \
ethtool \
exfatprogs \
exiv2 \
expac \
expat \
eza \
f2fs-tools \
faac \
faad2 \
fakeroot \
fastfetch \
fd \
ffmpeg \
ffmpeg4.4 \
ffmpegthumbnailer \
ffmpegthumbs \
fftw \
file \
filelight \
filesystem \
findutils \
firefox \
fish \
fish-autopair \
fish-pure-prompt \
fisher \
flac \
flashrom \
flex \
fluidsynth \
fmt \
fontconfig \
frameworkintegration \
freeglut \
freetype2 \
fribidi \
fsarchiver \
ftgl \
fuse-common \
fuse3 \
fwupd \
fwupd-efi \
fzf \
gawk \
gc \
gcc \
gcc-libs \
gcr-4 \
gdbm \
gdk-pixbuf2 \
gettext \
ghostscript \
giflib \
git \
glances \
glew \
glib-networking \
glib2 \
glibc \
glibmm \
glibmm-2.68 \
glm \
glslang \
glu \
glycin \
gmp \
gnulib-l10n \
gnupg \
gnutls \
gobject-introspection-runtime \
gperftools \
gpgme \
gpgmepp \
gpm \
graphene \
graphite \
grep \
groff \
gsettings-desktop-schemas \
gsettings-system-schemas \
gsm \
gssdp \
gssproxy \
gst-libav \
gst-plugin-pipewire \
gst-plugins-bad \
gst-plugins-bad-libs \
gst-plugins-base \
gst-plugins-base-libs \
gst-plugins-ugly \
gstreamer \
gtest \
gtk-update-icon-cache \
gtk3 \
gtk4 \
gtkmm-4.0 \
gtkmm3 \
gtksourceview4 \
guile \
gupnp \
gupnp-igd \
gwenview \
gzip \
harfbuzz \
haruna \
haveged \
hdparm \
hicolor-icon-theme \
hidapi \
highway \
hunspell \
hwdata \
hwdetect \
hwinfo \
hwloc \
i2c-tools \
iana-etc \
icu \
ijs \
imagemagick \
imath \
imlib2 \
inetutils \
inxi \
iproute2 \
iptables-nft \
iputils \
iso-codes \
iw \
iwd \
jack2 \
jansson \
jasper \
jbig2dec \
jbigkit \
jemalloc \
jfsutils \
jq \
json-c \
json-glib \
jsoncpp \
kaccounts-integration \
kactivitymanagerd \
karchive \
kate \
kauth \
kbd \
kbookmarks \
kcalc \
kcmutils \
kcodecs \
kcolorpicker \
kcolorscheme \
kcompletion \
kconfig \
kconfigwidgets \
kcontacts \
kcoreaddons \
kcrash \
kdbusaddons \
kde-cli-tools \
kde-gtk-config \
kdeclarative \
kdeconnect \
kdecoration \
kded \
kdegraphics-mobipocket \
kdegraphics-thumbnailers \
kdeplasma-addons \
kdesu \
kdialog \
kdnssd \
kdsingleapplication \
kdsoap-qt6 \
kdsoap-ws-discovery-client \
keyutils \
kfilemetadata \
kglobalaccel \
kglobalacceld \
kguiaddons \
kholidays \
ki18n \
kiconthemes \
kidletime \
kimageannotator \
kinfocenter \
kio \
kio-admin \
kio-extras \
kio-fuse \
kirigami \
kirigami-addons \
kitemmodels \
kitemviews \
kjobwidgets \
kmenuedit \
kmod \
knewstuff \
knotifications \
knotifyconfig \
konsole \
kpackage \
kparts \
kpeople \
kpipewire \
kpty \
kquickcharts \
krb5 \
krunner \
kscreen \
kscreenlocker \
kservice \
kstatusnotifieritem \
ksvg \
ksystemstats \
ktexteditor \
ktextwidgets \
kunitconversion \
kuserfeedback \
kwallet \
kwallet-pam \
kwalletmanager \
kwayland \
kwidgetsaddons \
kwin \
kwindowsystem \
kxmlgui \
l-smash \
lame \
lapack \
layer-shell-qt \
layer-shell-qt5 \
lcms2 \
ldb \
leancrypto \
less \
libaccounts-glib \
libaccounts-qt \
libaio \
libarchive \
libass \
libassuan \
libasyncns \
libatasmart \
libavc1394 \
libavtp \
libb2 \
libblockdev \
libblockdev-crypto \
libblockdev-fs \
libblockdev-loop \
libblockdev-mdraid \
libblockdev-nvme \
libblockdev-part \
libblockdev-swap \
libbluray \
libbpf \
libbs2b \
libbsd \
libbytesize \
libcaca \
libcanberra \
libcap \
libcap-ng \
libcbor \
libcddb \
libcdio \
libcdio-paranoia \
libcloudproviders \
libcolord \
libcups \
libdaemon \
libdatrie \
libdc1394 \
libdca \
libde265 \
libdecor \
libdeflate \
libdisplay-info \
libdmtx \
libdnet \
libdovi \
libdrm \
libdv \
libdvbpsi \
libdvdcss \
libdvdnav \
libdvdread \
libebml \
libebur128 \
libedit \
libei \
libelf \
libepoxy \
libevdev \
libevent \
libfakekey \
libfdk-aac \
libffi \
libfontenc \
libfreeaptx \
libftdi \
libfyaml \
libgcrypt \
libgirepository \
libgit2 \
libglvnd \
libgme \
libgoom2 \
libgpg-error \
libgsf \
libgudev \
libice \
libidn \
libidn2 \
libiec61883 \
libimobiledevice \
libimobiledevice-glue \
libinih \
libinput \
libisl \
libjcat \
libjpeg-turbo \
libjxl \
libkate \
libkdcraw \
libkexiv2 \
libksba \
libkscreen \
liblc3 \
libldac \
libldap \
liblqr \
liblrdf \
libltc \
libmad \
libmatroska \
libmaxminddb \
libmbim \
libmd \
libmfx \
libmicrodns \
libmm-glib \
libmng \
libmnl \
libmodplug \
libmpc \
libmpcdec \
libmpeg2 \
libmspack \
libmtp \
libmysofa \
libndp \
libnetfilter_conntrack \
libnewt \
libnfnetlink \
libnfs \
libnftnl \
libnghttp2 \
libnghttp3 \
libnice \
libnl \
libnm \
libnma-common \
libnma-gtk4 \
libnotify \
libnsl \
libnvme \
libogg \
liboggz \
libopenmpt \
libopenraw \
libp11-kit \
libpaper \
libpcap \
libpciaccess \
libpgm \
libpipeline \
libpipewire \
libplacebo \
libplasma \
libplist \
libpng \
libproxy \
libpsl \
libpulse \
libqaccessibilityclient-qt6 \
libqalculate \
libqmi \
libqrtr-glib \
libraqm \
libraw \
libraw1394 \
librsvg \
libsamplerate \
libsasl \
libseccomp \
libsecret \
libshout \
libsigc++ \
libsigc++-3.0 \
libsixel \
libsm \
libsndfile \
libsodium \
libsoup3 \
libsoxr \
libsrtp \
libssh \
libssh2 \
libstemmer \
libsysprof-capture \
libtasn1 \
libtatsu \
libteam \
libthai \
libtheora \
libtiff \
libtiger \
libtirpc \
libtommath \
libtool \
libunibreak \
libunistring \
libunwind \
libupnp \
liburcu \
liburing \
libusb \
libusb-compat \
libusbmuxd \
libutempter \
libuv \
libva \
libvdpau \
libverto \
libvlc \
libvorbis \
libvpl \
libvpx \
libwacom \
libwbclient \
libwebp \
libwireplumber \
libwnck3 \
libx11 \
libx86emu \
libxau \
libxaw \
libxcb \
libxcomposite \
libxcrypt \
libxcursor \
libxcvt \
libxdamage \
libxdmcp \
libxext \
libxfixes \
libxfont2 \
libxft \
libxi \
libxinerama \
libxkbcommon \
libxkbcommon-x11 \
libxkbfile \
libxml2 \
libxmlb \
libxmu \
libxpm \
libxpresent \
libxrandr \
libxrender \
libxres \
libxshmfence \
libxslt \
libxss \
libxt \
libxtst \
libxv \
libxxf86vm \
libzip \
licenses \
lilv \
linux-api-headers \
linux-cachyos \
linux-cachyos-headers \
linux-cachyos-lts \
linux-cachyos-lts-headers \
linux-firmware \
linux-firmware-amdgpu \
linux-firmware-atheros \
linux-firmware-broadcom \
linux-firmware-cirrus \
linux-firmware-intel \
linux-firmware-mediatek \
linux-firmware-nvidia \
linux-firmware-other \
linux-firmware-radeon \
linux-firmware-realtek \
linux-firmware-whence \
lirc \
live-media \
lld \
llhttp \
llvm \
llvm-libs \
lm_sensors \
lmdb \
logrotate \
lsb-release \
lsscsi \
lua \
luajit \
lv2 \
lvm2 \
lz4 \
lzo \
m4 \
mailcap \
make \
man-db \
man-pages \
md4c \
mdadm \
media-player-info \
meld \
mesa \
mesa-utils \
micro \
milou \
minizip \
mjpegtools \
mkinitcpio \
mkinitcpio-busybox \
mobile-broadband-provider-info \
modemmanager \
modemmanager-qt \
mpdecimal \
mpfr \
mpg123 \
mpv \
mpvqt \
mtdev \
mtools \
mujs \
nano \
nano-syntax-highlighting \
ncurses \
neon \
netctl \
nettle \
networkmanager \
networkmanager-openvpn \
networkmanager-qt \
networkmanager-vpn-plugin-openvpn \
nfs-utils \
nfsidmap \
nftables \
nilfs-utils \
noto-color-emoji-fontconfig \
noto-fonts \
noto-fonts-cjk \
noto-fonts-emoji \
npth \
nspr \
nss \
nss-mdns \
ntp \
numactl \
ocean-sound-theme \
ocl-icd \
octopi \
oh-my-zsh-git \
onetbb \
oniguruma \
open-vm-tools \
openal \
opencore-amr \
opencv \
opendesktop-fonts \
openexr \
openh264 \
openjpeg2 \
openssh \
openssl \
openvpn \
openxr \
opus \
orc \
p11-kit \
pacman \
pacman-contrib \
pacman-mirrorlist \
pacutils \
pahole \
pam \
pambase \
pango \
pangomm \
pangomm-2.48 \
parallel \
parted \
paru \
passim \
patch \
pavucontrol \
pciutils \
pcre \
pcre2 \
pcsclite \
perl \
perl-clone \
perl-encode-locale \
perl-error \
perl-file-listing \
perl-html-parser \
perl-html-tagset \
perl-http-cookiejar \
perl-http-cookies \
perl-http-daemon \
perl-http-date \
perl-http-message \
perl-http-negotiate \
perl-io-html \
perl-libwww \
perl-lwp-mediatypes \
perl-mailtools \
perl-net-http \
perl-timedate \
perl-try-tiny \
perl-uri \
perl-www-robotrules \
perl-xml-parser \
perl-xml-writer \
phonon-qt6 \
phonon-qt6-vlc \
pinentry \
pipewire \
pipewire-alsa \
pipewire-audio \
pipewire-pulse \
pixman \
pkcs11-helper \
pkgconf \
pkgfile \
plasma-activities \
plasma-activities-stats \
plasma-browser-integration \
plasma-desktop \
plasma-firewall \
plasma-integration \
plasma-nm \
plasma-pa \
plasma-systemmonitor \
plasma-thunderbolt \
plasma-workspace \
plasma5support \
plocate \
plymouth \
plymouth-kcm \
polkit \
polkit-kde-agent \
polkit-qt6 \
poppler \
poppler-data \
poppler-glib \
poppler-qt6 \
popt \
portaudio \
power-profiles-daemon \
powerdevil \
powerline-fonts \
ppp \
prison \
procps-ng \
projectm \
protobuf \
protobuf-c \
psmisc \
pulseaudio-qt \
purpose \
pv \
python \
python-annotated-types \
python-cairo \
python-defusedxml \
python-gobject \
python-orjson \
python-packaging \
python-psutil \
python-pydantic \
python-pydantic-core \
python-typing-inspection \
python-typing_extensions \
python-wxpython \
qca-qt6 \
qcoro \
qemu-guest-agent \
qqc2-breeze-style \
qqc2-desktop-style \
qrencode \
qt-sudo \
qt5-base \
qt5-declarative \
qt5-translations \
qt5-wayland \
qt6-5compat \
qt6-base \
qt6-connectivity \
qt6-declarative \
qt6-imageformats \
qt6-location \
qt6-multimedia \
qt6-multimedia-ffmpeg \
qt6-positioning \
qt6-quick3d \
qt6-quicktimeline \
qt6-sensors \
qt6-shadertools \
qt6-speech \
qt6-svg \
qt6-tools \
qt6-translations \
qt6-virtualkeyboard \
qt6-wayland \
qt6-webchannel \
qt6-webengine \
qt6-websockets \
qtermwidget \
raptor \
rate-mirrors \
rav1e \
re2 \
readline \
rebuild-detector \
reflector \
ripgrep \
ripgrep-all \
rpcbind \
rsync \
rtkit \
rtmpdump \
rubberband \
run-parts \
s-nail \
sbc \
scx-manager \
scx-scheds \
sd \
sddm \
sddm-kcm \
sdl12-compat \
sdl2-compat \
sdl3 \
sdl_image \
sed \
serd \
sg3_utils \
shaderc \
shadow \
shared-mime-info \
signon-kwallet-extension \
signon-plugin-oauth2 \
signon-ui \
signond \
slang \
smartmontools \
smbclient \
snappy \
socat \
sof-firmware \
solid \
sonnet \
sord \
sound-theme-freedesktop \
soundtouch \
spandsp \
spdlog \
spectacle \
speex \
speexdsp \
spice-vdagent \
spirv-tools \
sqlite \
sratom \
srt \
startup-notification \
sudo \
svt-av1 \
svt-hevc \
syndication \
syntax-highlighting \
sysfsutils \
systemd \
systemd-boot-manager \
systemd-libs \
systemd-resolvconf \
systemd-sysvcompat \
systemsettings \
taglib \
talloc \
tar \
tcl \
tdb \
tealdeer \
tevent \
texinfo \
thin-provisioning-tools \
tinysparql \
tpm2-tss \
tslib \
ttf-bitstream-vera \
ttf-dejavu \
ttf-fantasque-nerd \
ttf-fira-sans \
ttf-hack \
ttf-liberation \
ttf-meslo-nerd \
ttf-opensans \
twolame \
tzdata \
uchardet \
udisks2 \
ufw \
unrar \
unzip \
upower \
uriparser \
usb_modeswitch \
usbutils \
util-linux \
util-linux-libs \
v4l-utils \
vapoursynth \
verdict \
vi \
vid.stab \
vim \
vim-runtime \
virtualbox-guest-utils \
vlc-plugin-a52dec \
vlc-plugin-aalib \
vlc-plugin-alsa \
vlc-plugin-aom \
vlc-plugin-archive \
vlc-plugin-aribb24 \
vlc-plugin-aribb25 \
vlc-plugin-ass \
vlc-plugin-avahi \
vlc-plugin-bluray \
vlc-plugin-caca \
vlc-plugin-cddb \
vlc-plugin-chromecast \
vlc-plugin-dav1d \
vlc-plugin-dbus \
vlc-plugin-dbus-screensaver \
vlc-plugin-dca \
vlc-plugin-dvb \
vlc-plugin-dvd \
vlc-plugin-faad2 \
vlc-plugin-ffmpeg \
vlc-plugin-firewire \
vlc-plugin-flac \
vlc-plugin-fluidsynth \
vlc-plugin-freetype \
vlc-plugin-gme \
vlc-plugin-gnutls \
vlc-plugin-gstreamer \
vlc-plugin-inflate \
vlc-plugin-jack \
vlc-plugin-journal \
vlc-plugin-jpeg \
vlc-plugin-kate \
vlc-plugin-kwallet \
vlc-plugin-libsecret \
vlc-plugin-lirc \
vlc-plugin-live555 \
vlc-plugin-lua \
vlc-plugin-mad \
vlc-plugin-matroska \
vlc-plugin-mdns \
vlc-plugin-modplug \
vlc-plugin-mpeg2 \
vlc-plugin-mpg123 \
vlc-plugin-mtp \
vlc-plugin-musepack \
vlc-plugin-nfs \
vlc-plugin-notify \
vlc-plugin-ogg \
vlc-plugin-opus \
vlc-plugin-png \
vlc-plugin-pulse \
vlc-plugin-quicksync \
vlc-plugin-samplerate \
vlc-plugin-sdl \
vlc-plugin-sftp \
vlc-plugin-shout \
vlc-plugin-smb \
vlc-plugin-soxr \
vlc-plugin-speex \
vlc-plugin-srt \
vlc-plugin-svg \
vlc-plugin-tag \
vlc-plugin-theora \
vlc-plugin-twolame \
vlc-plugin-udev \
vlc-plugin-upnp \
vlc-plugin-vorbis \
vlc-plugin-vpx \
vlc-plugin-x264 \
vlc-plugin-x265 \
vlc-plugin-xml \
vlc-plugin-zvbi \
vlc-plugins-all \
vlc-plugins-base \
vlc-plugins-extra \
vlc-plugins-video-output \
vlc-plugins-visualization \
vmaf \
volume_key \
vulkan-icd-loader \
vulkan-mesa-device-select \
vulkan-tools \
vulkan-virtio \
wayland \
wayland-utils \
webrtc-audio-processing-1 \
wget \
which \
wildmidi \
wireless-regdb \
wireplumber \
wpa_supplicant \
wxwidgets-common \
wxwidgets-gtk3 \
x264 \
x265 \
xcb-proto \
xcb-util \
xcb-util-cursor \
xcb-util-image \
xcb-util-keysyms \
xcb-util-renderutil \
xcb-util-wm \
xdg-desktop-portal \
xdg-desktop-portal-gtk \
xdg-desktop-portal-kde \
xdg-user-dirs \
xdg-utils \
xf86-input-libinput \
xf86-input-vmmouse \
xfsprogs \
xkeyboard-config \
xl2tpd \
xmlsec \
xorg-fonts-encodings \
xorg-server \
xorg-server-common \
xorg-setxkbmap \
xorg-xauth \
xorg-xdpyinfo \
xorg-xinit \
xorg-xinput \
xorg-xkbcomp \
xorg-xkill \
xorg-xmessage \
xorg-xmodmap \
xorg-xprop \
xorg-xrandr \
xorg-xrdb \
xorg-xset \
xorg-xwayland \
xorgproto \
xsettingsd \
xvidcore \
xxhash \
xz \
yyjson \
zbar \
zeromq \
zimg \
zix \
zlib-ng \
zlib-ng-compat \
zram-generator \
zsh \
zsh-autosuggestions \
zsh-completions \
zsh-history-substring-search \
zsh-syntax-highlighting \
zsh-theme-powerlevel10k \
zstd \
zvbi \
zxing-cpp

print_status "Package installation completed"

# Step 3: System Configuration
print_section "Step 3: System Configuration"

print_info "Setting Plymouth boot animation..."
sudo plymouth-set-default-theme -R cachyos-bootanimation
print_status "Plymouth theme configured"

print_info "Configuring Fish shell..."
mkdir /home/$USER/.config/fish
cp -r /home/$USER/vanillaarch-to-cachyos/install-fullkde-grub/config.fish /home/$USER/.config/fish/config.fish
cp -r /home/$USER/vanillaarch-to-cachyos/install-fullkde-grub/.zshrc /home/$USER/.zshrc
sudo chmod +X /home/$USER/.config/fish/config.fish
chsh -s $(which fish)
print_status "Fish configuration applied"

print_info "Apply Cachyos Kde Theme..."
sudo chmod +x /home/$USER/vanillaarch-to-cachyos/install-fullkde-systemd-boot/installcachyostheme.sh
sudo chmod +x /home/$USER/vanillaarch-to-cachyos/install-fullkde-systemd-boot/start.sh
cd /home/$USER/vanillaarch-to-cachyos/install-fullkde-systemd-boot && ./installcachyostheme.sh
print_info "Theme Applied..."

print_section "CachyOS Conversion Complete!"
echo -e "${GREEN}${BOLD}"
echo "Conversion to CachyOS has been completed successfully!"
sudo rm -rf /home/$USER/vanillaarch-to-cachyos
echo "Please reboot your system to apply all changes."
echo -e "${NC}"
